openapi: 3.0.0
info:
  title: API Customer Orders
  version: 1.0.0
paths:
  /customers/{customerId}/orders:
    get:
      summary: Obtenir la liste des commandes d'un client
      description: Retourne la liste des commandes pour un client spécifique.
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
          description: L'ID du client pour lequel les commandes sont demandées.
      responses:
        '200':
          description: Liste des commandes retournée avec succès.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '404':
          description: Client non trouvé.
        '400':
          description: Requête invalide.

    post:
      summary: Ajouter une nouvelle commande pour un client
      description: Crée une nouvelle commande pour un client spécifique.
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
          description: L'ID du client pour lequel la commande est créée.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewOrder'
      responses:
        '201':
          description: Commande créée avec succès.
        '404':
          description: Client non trouvé.
        '400':
          description: Requête invalide.

  /customers/{customerId}/orders/{orderId}:
    put:
      summary: Mettre à jour une commande existante pour un client
      description: Met à jour une commande spécifique d'un client.
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
          description: L'ID du client pour lequel la commande est mise à jour.
        - in: path
          name: orderId
          required: true
          schema:
            type: string
          description: L'ID de la commande à mettre à jour.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Commande mise à jour avec succès.
        '404':
          description: Client ou commande non trouvée.
        '400':
          description: Requête invalide.

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          description: L'ID unique de la commande.
        reference:
          type: string
          description: La référence unique de la commande.
        meals:
          type: array
          items:
            type: object
            properties:
              mealId:
                type: string
              quantity:
                type: integer
                description: Quantité de meal commandée.
        orderDatetime:
          type: string
          format: date-time
          description: Date et heure de la commande (générée automatiquement par le serveur).
      required:
        - id
        - reference
        - meals
        - orderDatetime

    NewOrder:
      type: object
      properties:
        reference:
          type: string
          description: La référence unique de la commande.
        meals:
          type: array
          items:
            type: object
            properties:
              mealId:
                type: string
              quantity:
                type: integer
                description: Quantité de meal commandée.
      required:
        - reference
        - meals

